# Generated by Django 4.1.7 on 2023-03-08 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzbeschreibung', models.CharField(max_length=40, unique=True)),
                ('beschreibung', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('prio', models.CharField(max_length=10)),
                ('melder', models.CharField(max_length=40)),
                ('datum', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
